### ISSUE TITLE
Undefined symbol: PyUnicodeUCS2_Format

### ISSUE THREAD

**Issue by alexrd** [synapticarbors/wexplore-westpa#2]
Hi Josh!

I've finally checked out the wexplore implementation, and I'm running into some install problems.  I followed the procedure in the README, but I'm getting an error when I try to run init.sh in the CH4.CH4 folder:

`$ ./init.sh 
ln: creating symbolic link `./traj_segs': File exists
ln: creating symbolic link `./seg_logs': File exists
Traceback (most recent call last):
  File "/mnt/home/alexrd/westpa/lib/cmds/w_init.py", line 28, in <module>
    import westpa
  File "/mnt/home/alexrd/westpa/lib/west_tools/westpa/__init__.py", line 1, in <module>
    import _rc
  File "/mnt/home/alexrd/westpa/lib/west_tools/westpa/_rc.py", line 27, in <module>
    from yamlcfg import YAMLConfig
  File "/mnt/home/alexrd/westpa/lib/west_tools/westpa/yamlcfg.py", line 38, in <module>
    from westpa.binning import NopMapper
  File "/mnt/home/alexrd/westpa/lib/west_tools/westpa/binning/__init__.py", line 1, in <module>
    import assign, bins
  File "/mnt/home/alexrd/westpa/lib/west_tools/westpa/binning/assign.py", line 79, in <module>
    from _assign import output_map, apply_down, apply_down_argmin_across, rectilinear_assign #@UnresolvedImport
ImportError: /mnt/home/alexrd/westpa/lib/west_tools/westpa/binning/_assign.so: undefined symbol: PyUnicodeUCS2_Format
` 

Any thoughts on this?  Thanks for your help!

Alex

**Comment by synapticarbors** [comment]
@alexrd It looks like you're using a fork of this repo from @ajoshpratt, since he's added the CH4.CH4 example in his repo:

https://github.com/ajoshpratt/wexplore-westpa

But at first glance, it doesn't look like the problem is originating from the WExplore module, but instead has something to do with the compilation of `west_tools`. I believe the specific error you're seeing (from a quick google search) has something to do with an incompatibility between python installations and different unicode representations. Is it possible that you compiled WESTPA with one python install and then tried to run with another?

**Comment by astatide** [comment]
That looks to be the case to me, too.

@alexrd, that particular fork is also designed to be run with some specific branches of WESTPA and west_tools, as well.

For WESTPA: new_hooks
West_tools: recursive_update

This is because the WExplore plugin wasn't written to take advantage of recycling.  If you're not interested in recycling, this repo is the way to go.

**Comment by alexrd** [comment]
Yes I found the problem:  When I set up WESTPA it used some python libraries that I unknowingly had in LD_LIBRARY_PATH that were from a different version of Python.  After removing those (by unloading the Python module on the cluster here), this problem goes away and everything seems to be working well.  Thanks!
